QuanLyBanSach/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyBanSach.Models;

namespace QuanLyBanSach.Controllers
{
    public class CustomerController : Controller
    {
        private QL_BSEntities db = new QL_BSEntities();

        // GET: KHACHHANGs
        [HttpGet,ActionName("QuanLyKhachHang")]
        public ActionResult Index()
        {
            return View(db.KHACHHANG.ToList());
        }
        [Route]
        // GET: KHACHHANGs/Details/5
        [ActionName("ThongTinKhachHang")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANG.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // GET: KHACHHANGs/Create
        [Route]
        [ActionName("Register")]
        public ActionResult Create()
        {
            return View("Register");
        }

        // POST: KHACHHANGs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route]
        [HttpPost]
        [ActionName("Register")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MAKH,TENKH,EMAIL,MATKHAU,DIENTHOAI")] KHACHHANG kHACHHANG,FormCollection form)
        {
            var gioiTinh = form["gioiTinh"];
            var confirmedPassword = form["confirmedPassword"];
            KHACHHANG kh1 = db.KHACHHANG.SingleOrDefault(n => n.EMAIL == kHACHHANG.EMAIL);
            if (kh1 == null)
            {
                if (!String.IsNullOrEmpty(confirmedPassword))
                {
                    if (confirmedPassword.Equals(kHACHHANG.MATKHAU))
                    {
                        if (ModelState.IsValid)
                        {
                            db.KHACHHANG.Add(kHACHHANG);
                            db.SaveChanges();
                            return View("DangKyThanhCong");
                        }
                    }
                    else
                    {
                        ViewData["ConfirmedPassword"] = "Confirmed Password không trùng với Password";
                    }
                }else
                {
                    ViewBag.PasswordRong = "Confirmed Password không được bỏ trống";
                }
                
                
            }else
            {
                ViewBag.Email = "Email đã tồn tại .Mời bạn nhập email khác";
            }
            

            return View(kHACHHANG);
        }
        
        [HttpGet]
        [Route]
        [ActionName("Login")]
        public ActionResult DangNhap()
        {
            return View("Login");
        }
        
        [HttpPost]
        [Route]
        [ActionName("Login")]
        public ActionResult DangNhap(FormCollection collection)
        {
            var email = collection["email"];
            var password = collection["password"];
            var rememberMe = collection["rememberMe"];
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi1"] = "Email không được bỏ trống";
                
            } else if (String.IsNullOrEmpty(password)) {
                ViewData["Loi2"] = "Password không được bỏ trống";
            } else {
                KHACHHANG kh = db.KHACHHANG.SingleOrDefault(n => n.EMAIL == email && n.MATKHAU == password);
                if (kh != null)
                {
                    if (rememberMe != null)
                    {
                        if (rememberMe.Equals("true"))
                        {
                            Session["email"] = kh.EMAIL;
                            Session["password"] = kh.MATKHAU;
                        }
                    } else
                    {
                        Session["email"] = null;
                        Session["password"] = null;
                    }
                    Session["TaiKhoan"] = kh;
                    return RedirectToAction("TrangChu", "Home");
                } else
                {
                    ViewBag.ThongBao = "Email hoặc password không chính xác";
                }
            }
           
            return View();
        }
        [Route]
        [ActionName("Logout")]
        public ActionResult DangXuat()
        {
            Session["TaiKhoan"] = null;
            return RedirectToAction("TrangChu","Home");
        }

        // GET: KHACHHANGs/Edit/5
        [ActionName("ChinhSua")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANG.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // POST: KHACHHANGs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("ChinhSua")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MAKH,TENKH,HOKH,EMAIL,MATKHAU,DIENTHOAIKH")] KHACHHANG kHACHHANG,FormCollection form)
        {
            var gioiTinh = form["gioiTinh"];
            if (ModelState.IsValid)
            {
                db.Entry(kHACHHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kHACHHANG);
        }

      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyBanSach/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyBanSach.Models;

namespace QuanLyBanSach.Controllers
{
    public class DonHangController : Controller
    {
        private QL_BSEntities db = new QL_BSEntities();

        [HttpGet, ActionName("TrangDonHang")]
        // GET: DonHang
        public ActionResult Index(int? id)
        {
            var bills = db.DONHANG.Where(d => d.MAKH == id.Value).Include(s => s.CHITIETDONHANG);
            return View(bills.ToList());
        }

        // GET: DonHang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANG.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            return View(dONHANG);
        }

        // GET: DonHang/Create
        public ActionResult Create()
        {
            ViewBag.MAKH = new SelectList(db.KHACHHANG, "MAKH", "TENKH");
            return View();
        }

        // POST: DonHang/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MADONHANG,DIACHIGIAOHANG,NGAYDATHANG,NGAYGIAOHANG,TINHTRANG,DATHANHTOAN,MAKH,TONGTIEN")] DONHANG dONHANG)
        {
            if (ModelState.IsValid)
            {
                db.DONHANG.Add(dONHANG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MAKH = new SelectList(db.KHACHHANG, "MAKH", "TENKH", dONHANG.MAKH);
            return View(dONHANG);
        }

        // GET: DonHang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANG.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            ViewBag.MAKH = new SelectList(db.KHACHHANG, "MAKH", "TENKH", dONHANG.MAKH);
            return View(dONHANG);
        }

        // POST: DonHang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MADONHANG,DIACHIGIAOHANG,NGAYDATHANG,NGAYGIAOHANG,TINHTRANG,DATHANHTOAN,MAKH,TONGTIEN")] DONHANG dONHANG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dONHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MAKH = new SelectList(db.KHACHHANG, "MAKH", "TENKH", dONHANG.MAKH);
            return View(dONHANG);
        }

        // GET: DonHang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DONHANG dONHANG = db.DONHANG.Find(id);
            if (dONHANG == null)
            {
                return HttpNotFound();
            }
            return View(dONHANG);
        }

        // POST: DonHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DONHANG dONHANG = db.DONHANG.Find(id);
            db.DONHANG.Remove(dONHANG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyBanSach/Views/Customer/ChinhSua.cshtml
@model QuanLyBanSach.Models.KHACHHANG

@{
    ViewBag.Title = "Chỉnh sửa";
}
<head>
    <!-- Website CSS style -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="style.css">
</head>
<br /><br /><br />
<div style="max-width:1000px" class="alert alert-info">
    <h4>Chỉnh sửa thông tin khách hàng</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MAKH)

        <div class="form-group">
            @Html.LabelFor(model => model.TENKH, "Họ tên: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL,"Email: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EMAIL, null, new { @type = "email", @readonly = "readonly", @style = "border:none" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MATKHAU,"Password: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control",@type="password" } })
                @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIENTHOAI,"Số điện thoại: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIENTHOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon glyphicon-ok-sign"></span>  Lưu
                </button>
                <a href="@Url.Action("ThongTinKhachHang",new { id = Model.MAKH })" class="btn btn-danger"><span class="glyphicon glyphicon-remove-sign"></span> Hủy</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyBanSach/Views/Customer/DangKyThanhCong.cshtml
<script src="~/Scripts/bootstrap.min.js"></script>
@{
    ViewBag.Title = "DangKyThanhCong";
}

<h2>Bạn đã đăng ký thành công .Bấm vào đây để <a class="label label-default" href="@Url.Action("Login","Customer")">Đăng nhập</a></h2>

QuanLyBanSach/Views/Customer/Login.cshtml
@{
    Layout = null;
}

@using QuanLyBanSach.Models
@{
    ViewBag.Title = "Login";
}
<head>
    <meta charset="utf-8" />
    <link rel="icon" href="~/images/69.png">
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/base.css" rel="stylesheet" />
    <title>Login</title>
    <style>
        body {
            background-color: #044789;
        }
    </style>
</head>

<body>

    @using (Html.BeginForm("Login", "Customer", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Đăng nhập</div>
                    </div>
                    <div style="padding-top:30px" class="panel-body">
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12">
                            @if (ViewBag.ThongBao != null)
                            {
                                <p style="color:red">@ViewBag.ThongBao</p>
                            }
                        </div>

                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            @if (Session["email"] != null)
                            {
                                <input id="login-username" type="text" class="form-control" name="email" value="@Session["email"]" placeholder="me@gmail.com">

                            }
                            else
                            {
                                <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="me@gmail.com">

                            }

                        </div>
                        <p style="color:red">@ViewData["Loi1"]</p>
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            @if (Session["password"] != null)
                            {
                                <input id="login-password" type="password" value="@Session["password"]" class="form-control" name="password" placeholder="password">

                            }
                            else
                            {
                                <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                            }

                        </div>
                        <p style="color:red">
                            @ViewData["Loi2"]
                        </p>


                        <div class="input-group">
                            <div class="checkbox">
                                <label>
                                    <input id="login-remember" type="checkbox" name="rememberMe" value="true"> Remember me?
                                </label>
                            </div>
                        </div>

                        <div style="margin-top:10px;" class="form-group">
                            <!-- Button -->
                            <div class="col-sm-12 controls">
                                <input type="submit" value="Đăng nhập" class="btn btn-success" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 control">
                                <br />
                                <div style="border-top: 1px solid #888; padding-top:10px; font-size:90%">
                                    Không có tài khoản?
                                    <a href="@Url.Action("Register","Customer")">
                                        Đăng ký
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


    }

</body>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyBanSach/Views/Customer/QuanLyKhachHang.cshtml
@model IEnumerable<QuanLyBanSach.Models.KHACHHANG>
@using QuanLyBanSach.Models

@{

    ViewBag.Title = "Quản lý khách hàng";
}



@if (Session["TaiKhoan"] == null)
{
    <div class="row">
        <div class="center_column col-xs-12 col-sm-12">
            <div class="alert alert-danger" style="display:block">
                <div>
                    <span class="glyphicon glyphicon-warning-sign"></span>  Bạn không có quyền vô trang này
                </div>
            </div>
        </div>
    </div>
}
else
{
    <h2>Quản lý khách hàng</h2>
    <table class="table">
        <tr>
            <th>
                Tên khách hàng
            </th>
            <th>
                Email
            </th>
            <th>
                Điện Thoại
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.TENKH</td>

                <td>@item.EMAIL</td>
                <td>@item.DIENTHOAI</td>
                <td>
                    @*@Html.ActionLink("Sửa", "ChinhSua", new { id = item.MAKH })*@
                    @*@Html.ActionLink("Chi tiết", "ThongTinKhachHang", new { id = item.MAKH })*@
                    <a class="btn btn-primary" href="@Url.Action("ChinhSua","Customer",new { id = item.MAKH })">Sửa</a>
                    <a class="btn btn-primary" href="@Url.Action("ThongTinKhachHang","Customer",new { id = item.MAKH })">Chi tiết</a>
                    @*@Html.ActionLink("Xóa", "Delete", new { id=item.MAKH })*@
                </td>
            </tr>
        }

    </table>
}

QuanLyBanSach/Views/Customer/Register.cshtml
@model QuanLyBanSach.Models.KHACHHANG

@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/FooterCss.css" rel="stylesheet" />
    <!-- Website CSS style -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Website Font style -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="style.css">
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
    
</head>

<br />
<div class="alert alert-info">
    <h2>Đăng ký tài khoản</h2>
</div>
<p style="color:red">@ViewBag.Email</p>
<p style="color:red">@ViewBag.PasswordRong</p>
<p style="color:red">@ViewData["ConfirmedPassword"]</p>
    @using (Html.BeginForm("Register", "Customer", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="container">
            <div class="row mains">
                <div class="main-login main-center">
                    <div class="form-group">
                        <label for="name" class="cols-sm-2 control-label">Họ tên</label>
                        <div class="cols-md-5">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                                @Html.EditorFor(model => model.TENKH, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TENKH, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                 

                    <div class="form-group">
                        <label for="email" class="cols-sm-2 control-label">Email</label>
                        <div class="cols-md-5">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "me@gmail.com" } })
                                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })

                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="username" class="cols-sm-2 control-label">Số điện thoại</label>
                        <div class="cols-md-5">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                                @Html.EditorFor(model => model.DIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DIENTHOAI, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="cols-sm-2 control-label">Password</label>
                        <div class="cols-md-5">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-lock fa-lg"></i></span>
                                @Html.EditorFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control", placeholder = "password",@type="password" } })
                                @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="confirm" class="cols-sm-2 control-label">Confirmed Password</label>
                        <div class="cols-md-5">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-lock fa-lg"></i></span>
                                <input type="password" class="form-control" name="confirmedPassword" placeholder="nhập lại password" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group ">
                        <input type="submit" value="Đăng kí" class="btn btn-primary btn-lg login-button" />
                    </div>

                </div>
            </div>
        </div>
    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyBanSach/Views/Customer/ThongTinKhachHang.cshtml
@model QuanLyBanSach.Models.KHACHHANG

@{
    ViewBag.Title = "Thông tin khách hàng";
}

<head>

</head>
<br />
<body>


    <div class="row">
        <div class="center_column col-xs-12 col-sm-12">
            <div class="alert alert-info" style="display:block">
                <div>
                    <h4><span class="glyphicon glyphicon-user"></span> Thông tin khách hàng</h4>
                </div>
            </div>
        </div>
    </div>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                Tên
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TENKH)
            </dd>

            <dt>
                Email
            </dt>

            <dd style="pointer-events:none">
                @Html.TextBoxFor(model => model.EMAIL, null, new { @type = "email", @readonly = "readonly", @style = "border:none" })
            </dd>

            <dt>
                Số điện thoại
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DIENTHOAI)
            </dd>

        </dl>

    </div>
    <div class="row">
        <div class="col-sm-2">
            <a class="btn btn-default" href="@Url.Action("ChinhSua","Customer",new { id = Model.MAKH })">Chỉnh sửa thông tin</a>
        </div>
        <div class="col-sm-2">
            <a class="btn btn-primary" href="@Url.Action("TrangDonHang","DonHang",new { id = Model.MAKH })">Đơn hàng của bạn</a>
        </div>
    </div>
</body>