QuanLyBanSach/Models/SANPHAM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETDONHANG = new HashSet<CHITIETDONHANG>();
            this.CHITIETDONHANG_KDN = new HashSet<CHITIETDONHANG_KDN>();
            this.THONGTINKHUYENMAI = new HashSet<THONGTINKHUYENMAI>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public int MALOAI { get; set; }
        public int MANCC { get; set; }
        public string MOTA { get; set; }
        public int SOLUONGTON { get; set; }
        public bool TINHTRANG_HANG { get; set; }

        public string TinhTrangHang
        {
            get
            {
                return SOLUONGTON > 0 ? "Còn hàng" : "Hết hàng";
            }
        }

        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:#,###} VNĐ")]
        public decimal GIABAN { get; set; }
        public string ANHSP { get; set; }
    
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        public virtual ICollection<CHITIETDONHANG_KDN> CHITIETDONHANG_KDN { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual ICollection<THONGTINKHUYENMAI> THONGTINKHUYENMAI { get; set; }
    }
}

QuanLyBanSach/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyBanSach.Models;

namespace QuanLyBanSach.Controllers
{
    public class SanPhamController : Controller
    {
        private QL_BSEntities db = new QL_BSEntities();

        // GET: SanPham
        [ActionName("QuanLySanPham")]
        public ActionResult Index()
        {
            var sANPHAM = db.SANPHAM.Include(s => s.LOAISACH).Include(s => s.NHACUNGCAP);
            return View(sANPHAM.ToList());
        }

        // GET: SanPham/Create
        [ActionName("ThemSanPham")]
        public ActionResult Create()
        {
            ViewBag.MALOAI = new SelectList(db.LOAISACH, "MALOAI", "TENLOAI");
            ViewBag.MANCC = new SelectList(db.NHACUNGCAP, "MANCC", "TENNCC");
            return View();
        }

        // POST: SanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("ThemSanPham")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MASP,TENSP,MALOAI,MANCC,MOTA,SOLUONGTON,TINHTRANG_HANG,GIABAN,ANHSP")] SANPHAM sanPham, HttpPostedFileBase file)
        {
            sanPham.TINHTRANG_HANG = true;
            if (sanPham.SOLUONGTON <= 0) {
                ViewBag.ValidateSoLuong = "Số lượng không được nhỏ hơn 0";
                return View(sanPham);
            }
            this.uploadFile(sanPham,file);
            if (ModelState.IsValid)
            {
                db.SANPHAM.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("QuanLySanPham");
            }

            ViewBag.MALOAI = new SelectList(db.LOAISACH, "MALOAI", "TENLOAI", sanPham.MALOAI);
            ViewBag.MANCC = new SelectList(db.NHACUNGCAP, "MANCC", "TENNCC", sanPham.MANCC);
            return View(sanPham);
        }

        void uploadFile(SANPHAM sanPham, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                sanPham.ANHSP = fileName;
                var path = Path.Combine(Server.MapPath("~/images/"), fileName);
                file.SaveAs(path);
            } else
            {
                sanPham.ANHSP = "";
            }
        }

        // GET: SanPham/Edit/5
        [ActionName("SuaSanPham")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAM.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            ViewBag.MALOAI = new SelectList(db.LOAISACH, "MALOAI", "TENLOAI", sANPHAM.MALOAI);
            ViewBag.MANCC = new SelectList(db.NHACUNGCAP, "MANCC", "TENNCC", sANPHAM.MANCC);
            return View(sANPHAM);
        }

        // POST: SanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("SuaSanPham")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MASP,TENSP,MALOAI,MANCC,MOTA,SOLUONGTON,TINHTRANG_HANG,GIABAN,ANHSP")] SANPHAM sanPham, HttpPostedFileBase file)
        {
            sanPham.TINHTRANG_HANG = true;
            if (sanPham.SOLUONGTON <= 0)
            {
                ViewBag.ValidateSoLuong = "Số lượng không được nhỏ hơn 0";
                return View(sanPham);
            }
            this.uploadFile(sanPham, file);
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("QuanLySanPham");
            }
            ViewBag.MALOAI = new SelectList(db.LOAISACH, "MALOAI", "TENLOAI", sanPham.MALOAI);
            ViewBag.MANCC = new SelectList(db.NHACUNGCAP, "MANCC", "TENNCC", sanPham.MANCC);
            return View(sanPham);
        }

        // GET: SanPham/Delete/5
        [ActionName("XoaSanPham")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAM.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(sANPHAM);
        }

        // POST: SanPham/Delete/5
        [HttpPost, ActionName("XoaSanPham")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SANPHAM sANPHAM = db.SANPHAM.Find(id);
            db.SANPHAM.Remove(sANPHAM);
            db.SaveChanges();
            return RedirectToAction("QuanLySanPham");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyBanSach/Views/SanPham/Details.cshtml
@model QuanLyBanSach.Models.SANPHAM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SANPHAM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TENSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MOTA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MOTA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SOLUONGTON)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SOLUONGTON)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TINHTRANG_HANG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TINHTRANG_HANG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GIABAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIABAN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ANHSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ANHSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LOAISACH.TENLOAI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOAISACH.TENLOAI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHACUNGCAP.TENNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHACUNGCAP.TENNCC)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MASP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QuanLyBanSach/Views/SanPham/QuanLySanPham.cshtml
@model IEnumerable<QuanLyBanSach.Models.SANPHAM>

@{
    ViewBag.Title = "Quản lý sản phẩm";
}


<br />
<br />


@if (Session["TaiKhoan"] == null)
{
    <div class="row">
        <div class="center_column col-xs-12 col-sm-12">
            <div class="alert alert-danger" style="display:block">
                <div>
                    <span class="glyphicon glyphicon-warning-sign"></span>  Bạn không có quyền vô trang này
                </div>
            </div>
        </div>
    </div>
}
else
{
    <h2>Quản lý sản phẩm</h2>

    <p>
        <a class="btn btn-default" href="@Url.Action("ThemSanPham","SanPham")">Thêm</a>
        @*@Html.ActionLink("Thêm", "ThemSanPham")*@
    </p>
    <table class="table">
        <tr>
            <th>
                Tên sản phẩm
            </th>
            <th>
                Mô tả
            </th>
            <th>
               Số lượng
            </th>
            <th>
                Tình trạng
            </th>
            <th>
               Giá
            </th>
            <th>
                Ảnh
            </th>
            <th>
                Loại sách
            </th>
            <th>
                Nhà cung cấp
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TENSP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MOTA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SOLUONGTON)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TinhTrangHang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GIABAN)
                </td>
                <td>
                    @if (item.ANHSP == null)
                    {
                        <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/noimage.png" style="width: 150px; height: 200px;"> </a>
                    }
                    else if (!File.Exists(Server.MapPath("/images/" + item.ANHSP)))
                    {
                        <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/noimage.png" style="width: 150px; height: 200px;"> </a>

                    }
                    else if (!item.ANHSP.IsEmpty())
                    {
                        <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/@item.ANHSP" style="width: 150px; height: 200px;"> </a>
                    }
                    else 
                    {
                        <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/noimage.png" style="width: 150px; height: 200px;"> </a>
             
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LOAISACH.TENLOAI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NHACUNGCAP.TENNCC)
                </td>
                <td>
                    @*@Html.ActionLink("Sửa", "SuaSanPham", new { id = item.MASP }) |
                    @Html.ActionLink("Chi tiết", "ChiTietSanPham", "Home", new { id = item.MASP }) |
                    @Html.ActionLink("Xóa", "XoaSanPham", new { id = item.MASP })*@
                    <a class="btn btn-primary" href="@Url.Action("SuaSanPham","SanPham",new { id = item.MASP })">Sửa</a>
                    @*<a class="btn btn-primary" href="@Url.Action("ChiTietSanPham","Home",new { id = item.MASP })">Chi tiết</a>*@
                    <a class="btn btn-primary" href="@Url.Action("XoaSanPham","SanPham",new { id = item.MASP })">Xóa</a>
                </td>
            </tr>
        }

    </table>
}

QuanLyBanSach/Views/SanPham/SuaSanPham.cshtml
@model QuanLyBanSach.Models.SANPHAM

@{
    ViewBag.Title = "Quản lý sách";
}

<h2>Biễu mẫu</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MASP)

        <div class="form-group">
            @Html.LabelFor(model => model.TENSP,"Tên sách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MALOAI, "Loại sách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MALOAI, ViewBag.MALOAI as List<SelectListItem>, "---Select Status---")
                @Html.ValidationMessageFor(model => model.MALOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MANCC, "Nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MANCC, ViewBag.MANCC as List<SelectListItem>, "---Select Status---")
                @Html.ValidationMessageFor(model => model.MANCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MOTA,"Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SOLUONGTON,"Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SOLUONGTON, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SOLUONGTON, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.GIABAN,"Giá", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIABAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GIABAN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ANHSP,"Ảnh sách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" />
                @Html.ValidationMessageFor(model => model.ANHSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default" href="@Url.Action("QuanLySanPham","SanPham",new { id = Model.MASP })">Hủy</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyBanSach/Views/SanPham/ThemSanPham.cshtml
@model QuanLyBanSach.Models.SANPHAM

@{
    ViewBag.Title = "Thêm sản phẩm";
}

<h2>Biễu mẫu</h2>
@using (Html.BeginForm(null,null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TENSP,"Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MALOAI, "Loại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MALOAI, ViewBag.MALOAI as List<SelectListItem>,"---Select Status---")
                @Html.ValidationMessageFor(model => model.MALOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MANCC, "Nhà cung cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MANCC, ViewBag.MANCC as List<SelectListItem>, "---Select Status---")
                @Html.ValidationMessageFor(model => model.MANCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MOTA,"Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SOLUONGTON,"Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SOLUONGTON, new { htmlAttributes = new { @class = "form-control" } })
                <p style="color:red">@ViewBag.ValidateSoLuong</p>
                @Html.ValidationMessageFor(model => model.SOLUONGTON, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIABAN,"Giá", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIABAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GIABAN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ANHSP,"Ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ANHSP, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ANHSP, "", new { @class = "text-danger" })*@
                <input type="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyBanSach/Views/SanPham/XoaSanPham.cshtml
@model QuanLyBanSach.Models.SANPHAM

@{
    ViewBag.Title = "Xóa Sản phẩm";
}

<h3>Bạn có chắc chắn là muốn xóa sản phẩm này không?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sách
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENSP)
        </dd>

        <dt>
            Mô tả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MOTA)
        </dd>

        <dt>
           Số lượng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SOLUONGTON)
        </dd>

        <dt>
            Tình trạng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrangHang)
        </dd>

        <dt>
            Giá bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIABAN)
        </dd>

        <dt>
            Hình sản phẩm
        </dt>

        <dd>
            @if (Model.ANHSP == null)
            {
                <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/noimage.png" style="width: 150px; height: 180px;"> </a>
            }
            else if (!File.Exists(Server.MapPath("/images/" + Model.ANHSP)))
            {
                <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/noimage.png" style="width: 150px; height: 180px;"> </a>

            }
            else if (!Model.ANHSP.IsEmpty())
            {
                <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/@Model.ANHSP" style="width: 150px; height: 180px;"> </a>
            }
            else
            {
                <a style="pointer-events:none" class="thumbnail pull-left" href="#"> <img class="media-object" src="~/images/noimage.png" style="width: 150px; height: 180px;"> </a>

            }
        </dd>

        <dt>
            Loại sách
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOAISACH.TENLOAI)
        </dd>

        <dt>
            Nhà cung cấp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHACUNGCAP.TENNCC)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Xóa" class="btn btn-danger" /> 
        <a class="btn btn-default" href="@Url.Action("QuanLySanPham","SanPham",new { id = Model.MASP })">Hủy</a>
    </div>
    }
</div>